wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.32.0.dev0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693060730.285276
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      3:
      - 13
      - 23
      4: 3.11.4
      5: 0.15.8
      6: 4.32.0.dev0
      8:
      - 1
      - 4
      - 5
